name: Rust

on:
  push:
    branches: [ master, tmp ]
  pull_request:
    branches: [ master,tmp ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd demo/rlop && cargo build --release --verbose

