name: Rust

on:
  push:
    branches: [ master, gh-actions ]
  pull_request:
    branches: [ master, gh-actions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build rust
      run: cd demo/rlop && cargo build --release --verbose
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest -v
